// Export pages
export '/shared/shared_pages/welcome_and_login/welcome/welcome_widget.dart'
    show WelcomeWidget;
export '/shared/shared_pages/welcome_and_login/login/login_widget.dart'
    show LoginWidget;
export '/storage_keeper/sk_pages/storekeeper_home/storekeeper_home_widget.dart'
    show StorekeeperHomeWidget;
export '/under_test/pages_under_test/home01_company_list/home01_company_list_widget.dart'
    show Home01CompanyListWidget;
export '/admin/a_pages/create_user/create_user_widget.dart'
    show CreateUserWidget;
export '/storage_keeper/sk_pages/missingtools_form/missingtools_form_widget.dart'
    show MissingtoolsFormWidget;
export '/storage_keeper/sk_pages/day_contract_list/day_contract_list_widget.dart'
    show DayContractListWidget;
export '/storage_keeper/sk_pages/request_details/request_details_widget.dart'
    show RequestDetailsWidget;
export '/admin/a_pages/create_user_2/create_user2_widget.dart'
    show CreateUser2Widget;
export '/supervisor/sv_pages/supervisor_home/supervisor_home_widget.dart'
    show SupervisorHomeWidget;
export '/admin/a_pages/admin_home/admin_home_widget.dart' show AdminHomeWidget;
export '/shared/shared_pages/my_profile/my_profile_widget.dart'
    show MyProfileWidget;
export '/worker/worker_home/worker_home_widget.dart' show WorkerHomeWidget;
export '/storage_keeper/sk_pages/transmission_select_1/transmission_select1_widget.dart'
    show TransmissionSelect1Widget;
export '/storage_keeper/sk_pages/transmission_scan_2/transmission_scan2_widget.dart'
    show TransmissionScan2Widget;
export '/shared/shared_pages/welcome_and_login/how_to_use_app/how_to_use_app_widget.dart'
    show HowToUseAppWidget;
export '/shared/shared_pages/welcome_and_login/checkup/checkup_widget.dart'
    show CheckupWidget;
export '/supplier/supplier_dashboard/supplier_dashboard_widget.dart'
    show SupplierDashboardWidget;
export '/shared/shared_pages/applyforjob/applyforjob_widget.dart'
    show ApplyforjobWidget;
export '/under_test/pages_under_test/onboarding04/onboarding04_widget.dart'
    show Onboarding04Widget;
export '/shared/hint_beforeapplyjob/hint_beforeapplyjob_widget.dart'
    show HintBeforeapplyjobWidget;
export '/under_test/pages_under_test/home13_productivity/home13_productivity_widget.dart'
    show Home13ProductivityWidget;
export '/supervisor/sv_pages/tasks_tracker/tasks_tracker_widget.dart'
    show TasksTrackerWidget;
export '/under_test/pages_under_test/complain_form_copy/complain_form_copy_widget.dart'
    show ComplainFormCopyWidget;
export '/admin/a_pages/users_list/users_list_widget.dart' show UsersListWidget;
export '/shared/shared_pages/user_profile/user_profile_widget.dart'
    show UserProfileWidget;
export '/list/list_widget.dart' show ListWidget;
export '/settings1_notifications/settings1_notifications_widget.dart'
    show Settings1NotificationsWidget;
export '/admin/a_pages/update_user/update_user_widget.dart'
    show UpdateUserWidget;
export '/working_area/working_area_widget.dart' show WorkingAreaWidget;
export '/supervisor/sv_pages/sv_requests/sv_requests_widget.dart'
    show SvRequestsWidget;
export '/supervisor/sv_pages/attendanceofworkers/attendanceofworkers_widget.dart'
    show AttendanceofworkersWidget;
export '/supervisor/sv_pages/sv_map/sv_map_widget.dart' show SvMapWidget;
export '/supervisor/sv_pages/attendenceof_supervisor/attendenceof_supervisor_widget.dart'
    show AttendenceofSupervisorWidget;
export '/supervisor/sv_pages/loggingout_for_supervisor/loggingout_for_supervisor_widget.dart'
    show LoggingoutForSupervisorWidget;
export '/supervisor/sv_pages/submitting_complaints/submitting_complaints_widget.dart'
    show SubmittingComplaintsWidget;
export '/supervisor/sv_pages/daily_report/daily_report_widget.dart'
    show DailyReportWidget;
export '/supervisor/sv_pages/submitting_personal_requests/submitting_personal_requests_widget.dart'
    show SubmittingPersonalRequestsWidget;
export '/supervisor/sv_pages/taskdetails/taskdetails_widget.dart'
    show TaskdetailsWidget;
export '/supervisor/sv_pages/loggingout_for_workers/loggingout_for_workers_widget.dart'
    show LoggingoutForWorkersWidget;
export '/supervisor/sv_pages/workers_review/workers_review_widget.dart'
    show WorkersReviewWidget;
export '/details_area/details_area_widget.dart' show DetailsAreaWidget;
export '/traffic_manager/tm_pages/tm_home/tm_home_widget.dart'
    show TmHomeWidget;
export '/create04_task/create04_task_widget.dart' show Create04TaskWidget;
export '/traffic_manager/tm_pages/movment/movment_widget.dart'
    show MovmentWidget;
export '/traffic_manager/tm_pages/add_servicingreport/add_servicingreport_widget.dart'
    show AddServicingreportWidget;
export '/traffic_manager/tm_pages/tm_list_requests/tm_list_requests_widget.dart'
    show TmListRequestsWidget;
export '/traffic_manager/tm_pages/tm_task_discription/tm_task_discription_widget.dart'
    show TmTaskDiscriptionWidget;
export '/traffic_manager/tm_pages/servicing_discription/servicing_discription_widget.dart'
    show ServicingDiscriptionWidget;
export '/traffic_manager/tm_pages/tm_list_fixing/tm_list_fixing_widget.dart'
    show TmListFixingWidget;
export '/supervisor/sv_pages/form_for_lated_task/form_for_lated_task_widget.dart'
    show FormForLatedTaskWidget;
export '/taskdetails_copy/taskdetails_copy_widget.dart'
    show TaskdetailsCopyWidget;
export '/sv_requests_copy/sv_requests_copy_widget.dart'
    show SvRequestsCopyWidget;
