// Export pages
export '/traffic_manager/shared/shared_pages/welcome_and_login/welcome/welcome_widget.dart'
    show WelcomeWidget;
export '/traffic_manager/shared/shared_pages/login/login_widget.dart'
    show LoginWidget;
export '/storage_keeper/sk_pages/storekeeper_home/storekeeper_home_widget.dart'
    show StorekeeperHomeWidget;
export '/under_test/pages_under_test/home01_company_list/home01_company_list_widget.dart'
    show Home01CompanyListWidget;
export '/admin/a_pages/create_user/create_user_widget.dart'
    show CreateUserWidget;
export '/storage_keeper/sk_pages/missingtools_form/missingtools_form_widget.dart'
    show MissingtoolsFormWidget;
export '/storage_keeper/sk_pages/day_contract_list/day_contract_list_widget.dart'
    show DayContractListWidget;
export '/storage_keeper/sk_pages/request_details/request_details_widget.dart'
    show RequestDetailsWidget;
export '/admin/a_pages/create_user_2/create_user2_widget.dart'
    show CreateUser2Widget;
export '/supervisor/sv_pages/supervisor_home/supervisor_home_widget.dart'
    show SupervisorHomeWidget;
export '/admin/a_pages/admin_home/admin_home_widget.dart' show AdminHomeWidget;
export '/traffic_manager/shared/shared_pages/my_profile/my_profile_widget.dart'
    show MyProfileWidget;
export '/worker/worker_home/worker_home_widget.dart' show WorkerHomeWidget;
export '/storage_keeper/sk_pages/transmission_select_1/transmission_select1_widget.dart'
    show TransmissionSelect1Widget;
export '/storage_keeper/sk_pages/transmission_scan_2/transmission_scan2_widget.dart'
    show TransmissionScan2Widget;
export '/traffic_manager/shared/shared_pages/welcome_and_login/how_to_use_app/how_to_use_app_widget.dart'
    show HowToUseAppWidget;
export '/traffic_manager/shared/shared_pages/checkup/checkup_widget.dart'
    show CheckupWidget;
export '/supplier/supplier_dashboard/supplier_dashboard_widget.dart'
    show SupplierDashboardWidget;
export '/traffic_manager/shared/shared_pages/applyforjob/applyforjob_widget.dart'
    show ApplyforjobWidget;
export '/under_test/pages_under_test/onboarding04/onboarding04_widget.dart'
    show Onboarding04Widget;
export '/traffic_manager/shared/hint_beforeapplyjob/hint_beforeapplyjob_widget.dart'
    show HintBeforeapplyjobWidget;
export '/under_test/pages_under_test/home13_productivity/home13_productivity_widget.dart'
    show Home13ProductivityWidget;
export '/supervisor/sv_pages/tasks_tracker/tasks_tracker_widget.dart'
    show TasksTrackerWidget;
export '/under_test/pages_under_test/complain_form_copy/complain_form_copy_widget.dart'
    show ComplainFormCopyWidget;
export '/admin/a_pages/users_list/users_list_widget.dart' show UsersListWidget;
export '/under_test/pages_under_test/list/list_widget.dart' show ListWidget;
export '/under_test/pages_under_test/settings1_notifications/settings1_notifications_widget.dart'
    show Settings1NotificationsWidget;
export '/supervisor/sv_pages/sv_work_requests/sv_work_requests_widget.dart'
    show SvWorkRequestsWidget;
export '/supervisor/sv_pages/attendanceofworkers/attendanceofworkers_widget.dart'
    show AttendanceofworkersWidget;
export '/supervisor/sv_pages/sv_map/sv_map_widget.dart' show SvMapWidget;
export '/supervisor/sv_pages/attendenceof_supervisor/attendenceof_supervisor_widget.dart'
    show AttendenceofSupervisorWidget;
export '/supervisor/sv_pages/loggingout_for_supervisor/loggingout_for_supervisor_widget.dart'
    show LoggingoutForSupervisorWidget;
export '/supervisor/sv_pages/submitting_complaints/submitting_complaints_widget.dart'
    show SubmittingComplaintsWidget;
export '/supervisor/sv_pages/daily_report/daily_report_widget.dart'
    show DailyReportWidget;
export '/supervisor/sv_pages/taskdetails/taskdetails_widget.dart'
    show TaskdetailsWidget;
export '/supervisor/sv_pages/loggingout_for_workers/loggingout_for_workers_widget.dart'
    show LoggingoutForWorkersWidget;
export '/supervisor/sv_pages/workers_review/workers_review_widget.dart'
    show WorkersReviewWidget;
export '/under_test/pages_under_test/details_area/details_area_widget.dart'
    show DetailsAreaWidget;
export '/traffic_manager/tm_pages/tm_home/tm_home_widget.dart'
    show TmHomeWidget;
export '/traffic_manager/tm_pages/add_movement/add_movement_widget.dart'
    show AddMovementWidget;
export '/traffic_manager/tm_pages/add_servicingreport/add_servicingreport_widget.dart'
    show AddServicingreportWidget;
export '/traffic_manager/tm_pages/tm_list_requests/tm_list_requests_widget.dart'
    show TmListRequestsWidget;
export '/traffic_manager/tm_pages/tm_task_discription/tm_task_discription_widget.dart'
    show TmTaskDiscriptionWidget;
export '/traffic_manager/tm_pages/servicing_discription/servicing_discription_widget.dart'
    show ServicingDiscriptionWidget;
export '/traffic_manager/tm_pages/tm_list_fixing/tm_list_fixing_widget.dart'
    show TmListFixingWidget;
export '/supervisor/sv_pages/form_for_lated_task/form_for_lated_task_widget.dart'
    show FormForLatedTaskWidget;
export '/under_test/pages_under_test/taskdetails_copy/taskdetails_copy_widget.dart'
    show TaskdetailsCopyWidget;
export '/under_test/pages_under_test/sv_requests_copy/sv_requests_copy_widget.dart'
    show SvRequestsCopyWidget;
export '/supplier/supllier_home/supllier_home_widget.dart'
    show SupllierHomeWidget;
export '/supervisor/sv_pages/send_personal_request/send_personal_request_widget.dart'
    show SendPersonalRequestWidget;
export '/operation_maneger_s/workersattendance/workersattendance_widget.dart'
    show WorkersattendanceWidget;
export '/under_test/pages_under_test/home/home_widget.dart' show HomeWidget;
export '/under_test/pages_under_test/home19_property_appbookingapp/home19_property_appbookingapp_widget.dart'
    show Home19PropertyAppbookingappWidget;
export '/under_test/pages_under_test/rr/rr_widget.dart' show RrWidget;
export '/operation_maneger_s/o_m_pages/list_complaints/list_complaints_widget.dart'
    show ListComplaintsWidget;
export '/operation_maneger_s/o_m_pages/o_m_home/o_m_home_widget.dart'
    show OMHomeWidget;
export '/under_test/pages_under_test/details03_transactions_summary/details03_transactions_summary_widget.dart'
    show Details03TransactionsSummaryWidget;
export '/operation_maneger_s/o_m_pages/o_m_complandiscription/o_m_complandiscription_widget.dart'
    show OMComplandiscriptionWidget;
export '/operation_maneger_s/o_m_pages/o_m_list_work_orders/o_m_list_work_orders_widget.dart'
    show OMListWorkOrdersWidget;
export '/operation_maneger_s/o_m_pages/o_m_work_orders_discription/o_m_work_orders_discription_widget.dart'
    show OMWorkOrdersDiscriptionWidget;
export '/admin/a_pages/list_reviews/list_reviews_widget.dart'
    show ListReviewsWidget;
export '/under_test/pages_under_test/dash2/dash2_widget.dart' show Dash2Widget;
export '/traffic_manager/shared/shared_pages/maps/list_maps/list_maps_widget.dart'
    show ListMapsWidget;
export '/traffic_manager/shared/shared_pages/maps/add_maps/add_maps_widget.dart'
    show AddMapsWidget;
export '/admin/a_pages/user_profile/user_profile_widget.dart'
    show UserProfileWidget;
export '/admin/a_pages/update_user/update_user_widget.dart'
    show UpdateUserWidget;
export '/under_test/pages_under_test/details20_property/details20_property_widget.dart'
    show Details20PropertyWidget;
export '/operation_maneger_s/o_m_pages/o_m_list_all_task/o_m_list_all_task_widget.dart'
    show OMListAllTaskWidget;
export '/operation_maneger_s/o_m_pages/o_m_supmited_task_detalis/o_m_supmited_task_detalis_widget.dart'
    show OMSupmitedTaskDetalisWidget;
export '/operation_maneger_s/o_m_pages/o_m_list_all_daily_reports/o_m_list_all_daily_reports_widget.dart'
    show OMListAllDailyReportsWidget;
export '/operation_maneger_s/o_m_pages/o_m_view_daily_report/o_m_view_daily_report_widget.dart'
    show OMViewDailyReportWidget;
export '/operation_maneger_s/o_m_pages/o_m_list_personal_orders/o_m_list_personal_orders_widget.dart'
    show OMListPersonalOrdersWidget;
export '/operation_maneger_s/o_m_pages/o_m_personal_orders_discription/o_m_personal_orders_discription_widget.dart'
    show OMPersonalOrdersDiscriptionWidget;
export '/operation_maneger_s/o_m_pages/o_m_view_distribution_of_workers/o_m_view_distribution_of_workers_widget.dart'
    show OMViewDistributionOfWorkersWidget;
export '/operation_maneger_s/o_m_pages/o_m_list_distribution_of_workers/o_m_list_distribution_of_workers_widget.dart'
    show OMListDistributionOfWorkersWidget;
export '/admin/a_pages/new_admin_home/new_admin_home_widget.dart'
    show NewAdminHomeWidget;
export '/under_test/pages_under_test/home07_invoices/home07_invoices_widget.dart'
    show Home07InvoicesWidget;
export '/admin/a_pages/manualattendance/manualattendance_widget.dart'
    show ManualattendanceWidget;
export '/other_home/other_home_widget.dart' show OtherHomeWidget;
export '/traffic_manager/shared/shared_pages/maps/view_location/view_location_widget.dart'
    show ViewLocationWidget;
export '/traffic_manager/shared/shared_pages/maps/set_street_supervisor/set_street_supervisor_widget.dart'
    show SetStreetSupervisorWidget;
export '/operation_maneger_s/o_m_pages/other_services/other_services_widget.dart'
    show OtherServicesWidget;
export '/suc/suc_widget.dart' show SucWidget;
export '/traffic_manager/tm_pages/new_tm_home/new_tm_home_widget.dart'
    show NewTmHomeWidget;
export '/supervisor/sv_pages/choose_workers_manual/choose_workers_manual_widget.dart'
    show ChooseWorkersManualWidget;
export '/operation_maneger_s/o_m_pages/accountant_home/accountant_home_widget.dart'
    show AccountantHomeWidget;
export '/supplier_transactions/supplier_transactions_widget.dart'
    show SupplierTransactionsWidget;
export '/admin/a_pages/add_transactions/add_transactions_widget.dart'
    show AddTransactionsWidget;
export '/admin/a_pages/contractors_list/contractors_list_widget.dart'
    show ContractorsListWidget;
export '/operation_maneger_s/o_m_pages/o_m_cars_orders_discription/o_m_cars_orders_discription_widget.dart'
    show OMCarsOrdersDiscriptionWidget;
export '/under_test/pages_under_test/create04_task_copy/create04_task_copy_widget.dart'
    show Create04TaskCopyWidget;
export '/sw_eng/eng_home/eng_home_widget.dart' show EngHomeWidget;
export '/sw_eng/eng_list_technicalsupport/eng_list_technicalsupport_widget.dart'
    show EngListTechnicalsupportWidget;
export '/sw_eng/eng_technicalsupport_details/eng_technicalsupport_details_widget.dart'
    show EngTechnicalsupportDetailsWidget;
export '/sw_eng/send_technicalsupport/send_technicalsupport_widget.dart'
    show SendTechnicalsupportWidget;
export '/traffic_manager/tm_pages/tm_list_movment/tm_list_movment_widget.dart'
    show TmListMovmentWidget;
